### ISSUE TITLE
Issues Page Design Ideas

### ISSUE THREAD

**Issue by moollaza** [duckduckgo/duckduckhack.com#24]
Below are some potential improvements I think we should consider making to the [issues](https://duckduckhack.com/issues) page

1. Set a max-width on the issues table, and center align it for wide screens. 
  Currently the table just grows to fill the page width making it look odd on large, wide screens
2. Allow the user to sort the issues by difficult, or skill. This way the user can more easily scan the page for "easy" issues or issues that match a certain skill. Being able to filter the page may be even better

---
/cc @loganom

**Comment by pjhampton** [comment]
Currently, there are two types of issues; issues _to work on_ and discussion type issues that aren't actionable without some discussion. I think it would be great if we could distinguish between these two kinds in the table somehow. 

Some other potential ideas include:

- Add the repo type to the table: Spice, Goodie, Fathead and Longtail
- It's not always possible to assign someone an issue. This could be because they don't belong to the DDG Github org. Make it invisible if the _work in progress_ label is present.

**Comment by EcutDavid** [comment]
HI @moollaza, I really want to work on this task but I'm not good design UI/UX. 

Can you provide mockup for things below?
1. Filter.
2. Search bar.
3. "More than two skills don't look great (see screenshot 1). We should discuss how to handle this."


Not sure about "Add the repo type to the table: Spice, Goodie, Fathead and Longtail" . 
I'm new to duckduckgo, are these 4 the main products?

**Comment by pjhampton** [comment]
This can be closed down for now 👍  We can discuss improving this in a v2
